In [1]:
import tensorflow as tf

In [2]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' #TO REMOVE ERROR MESSAGES

In [33]:
physical_devices = tf.config.list_physical_devices('GPU')

## Intialization a tensor

In [3]:
x = tf.constant(4)

In [4]:
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [6]:
tf.constant(4,shape=(1,1), dtype = tf.float32)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [7]:
tf.constant([[1,2,3],[4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [8]:
tf.ones((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [9]:
tf.zeros((2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [10]:
tf.eye(3)   # indentical matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [11]:
tf.random.normal((3,3),mean=0,stddev=1)   # to generate normal distribution

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.27200142, -0.5659291 ,  0.5432948 ],
       [-0.8035494 ,  0.03074717,  1.0086639 ],
       [-0.5341714 , -0.06863499, -0.7086583 ]], dtype=float32)>

In [12]:
tf.random.uniform((1,3),minval=0,maxval=1)   # to generate uniform distribution

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.3843404 , 0.15789843, 0.28712416]], dtype=float32)>

In [13]:
tf.range(9)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [14]:
tf.range(start=1,limit=10,delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [15]:
x = tf.cast(x, dtype=tf.float64)  #type casting

In [16]:
x

<tf.Tensor: shape=(), dtype=float64, numpy=4.0>

## Mathematical operations

In [17]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

In [18]:
z = tf.add(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10])>

In [19]:
x+y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10])>

In [20]:
tf.subtract(x, y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4])>

In [21]:
x-y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-8, -6, -4])>

In [22]:
tf.divide(x,y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [23]:
x/y

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [24]:
tf.multiply(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21])>

In [25]:
x*y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21])>

In [27]:
tf.tensordot(x,y, axes = 1)

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [28]:
tf.reduce_sum(x*y, axis = 0)

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [29]:
x ** 5

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1,  32, 243])>

In [30]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))

In [31]:
tf.matmul(x,y)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.20189664,  0.39852282, -1.693748  ,  2.9267514 ],
       [-0.489925  , -0.47693056, -0.05037171, -3.6312652 ]],
      dtype=float32)>

In [32]:
x @ y

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.20189664,  0.39852282, -1.693748  ,  2.9267514 ],
       [-0.489925  , -0.47693056, -0.05037171, -3.6312652 ]],
      dtype=float32)>

## Indexing

In [35]:
x = tf.constant([0,1,1,2,3,1,2,3])

In [36]:
x[:]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 1, 2, 3, 1, 2, 3])>

In [37]:
x[1:]

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([1, 1, 2, 3, 1, 2, 3])>

In [38]:
x[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1])>

In [39]:
x[::2]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 3, 2])>

In [40]:
x[::-1]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([3, 2, 1, 3, 2, 1, 1, 0])>

In [41]:
indices = tf.constant([0,3])

In [42]:
x_ind = tf.gather(x,indices)

In [43]:
x_ind

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2])>

In [44]:
x = tf.constant([[1,2],
                [3,4],
                [5,6]])

In [45]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [48]:
x[0,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [49]:
x[0:2,:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

## Reshaping

In [50]:
x = tf.range(9)

In [51]:
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [52]:
x = tf.reshape(x,(3,3))

In [53]:
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [54]:
tf.transpose(x,perm=[1,0])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])>